{
 "title": "Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Prometheus total HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}} load" }
   ]
  },
  {
   "title": "Bind average query reponse time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bind_resolver_query_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Syslog messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "timestamp" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}