- name: setup bind and dns records
  hosts: dns
  become: yes
  tasks:
    - name: Install bind9
      apt: 
        name=bind9 
        update_cache=yes 
        state=latest

    - name: configure bind
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify:
        - restart bind
        - check conf

    - name: configure bind.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify:
        - restart bind
        - check conf

    - name: check zone hash
      copy:
        content: "{{ records|hash }}"
        dest: /etc/bind/db.shibra.hash
      when: dns_role == "master"
      notify:
        - get timestamp
        - upload bind zone
        - restart bind
        - bind reload db

    - name: config db ptr
      template:
        src: templates/db.shibra.ptr.j2
        dest: /etc/bind/db.shibra.ptr
      when: dns_role == "master"
      notify:
        - restart bind
        - bind reload db

    - name: update dns servers in resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

  handlers:
    - name: check conf
      shell: named-checkconf

    - name: restart bind
      service:
        name: bind9
        state: restarted

    - name: bind reload db
      shell: rndc reload

    - name: get timestamp
      shell: "date +%s"
      register: timestamp

    - name: upload bind zone
      template:
        src: templates/db.shibra.j2
        dest: /etc/bind/db.shibra