- name: Install MySQL
  apt: 
    name=mysql-server
    update_cache=yes 
    state=latest

- name: Install python modules for ansible
  apt: 
    name: ['python-pymysql', 'python3-pymysql', 'python-mysqldb']
    update_cache: yes 
    state: latest
    
- name: Start Mysql Service
  service: 
    name: mysql 
    state: started 
    enabled: true

- name: Create database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present

- name: Create user 
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "{{ mysql_host }}"
    login_host: "{{ mysql_login_host }}"
    priv: '{{db_name}}.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create user 
  mysql_user:
    name: "prometheus"
    password: "{{ prometheus_db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: listen on 0.0.0.0 if not already
  ini_file:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: "bind-address"
    value: "{{ mysql_bind_address }}"
  notify:
    - restart mysql
    
