---
- name: First play
  hosts: all
  become: yes
  tasks:
  - name: Get processes
    command: "ps -A"
    register: processes
  
  - name: Show processes
    debug:
      var: processes.stdout_lines
      
  - name: Ensure 'sysadmins' group exists
    group:
      name: sysadmins
      state: present
  
  - name: Create users 'romankuchin' and 'hudolejev' part of 'sysadmins' group
    user:
      name: "{{ item }}"
      shell: /bin/bash
      group: sysadmins
      append: yes
    with_items:
    - romankuchin
    - hudolejev
  
  - name: Add SSH keys for users 'romankuchin' and 'hudolejev'
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ item.key }}"
      state: present
    with_items:
     - { name: romankuchin, key: "https://github.com/romankuchin.keys" }
     - { name: hudolejev, key: "https://github.com/hudolejev.keys" }
     
  - name: Disable sudo password for created users
    copy:
      dest: /etc/sudoers.d/{{ item }}
      content: "{{ item }}      ALL = NOPASSWD: ALL"
    with_items:
    - romankuchin
    - hudolejev
    - dev