- name: Setup backup manager
  hosts: backup-agent
  become: yes
  tasks:
    - name: Create backup user
      user:
        name: "{{ backup_user }}"
        shell: /bin/bash

    - name: Create a directory if it does not exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0775'
        owner: "{{ backup_user }}"
        group: "{{ backup_user }}"
      with_items:
      - "/var/backup"
      - "/var/backup/sql"
      - "/var/backup/dns"
      - "/var/backup/wordpress"

    - name: Copy file with owner and permissions
      copy:
        src: "{{ item }}"
        dest: "/home/{{ backup_user }}/.ssh/"
        mode: 0600
        owner: "{{ backup_user }}"
        group: "{{ backup_user }}"
      with_fileglob:
        - keys/*