- name: Check that the file exists
  stat:
    path: /root/go/src/github.com/digitalocean/bind_exporter/bind_exporter.go
  register: stat_result

- name: go get
  shell: "go get github.com/digitalocean/bind_exporter"
  when: stat_result.stat.exists == False

- name: copy binary
  copy:
    src: /root/go/bin/bind_exporter
    dest: /usr/local/bin/bind_exporter
    mode: u=rwx,g=rx,o=rx
    remote_src: yes

- name: make a service
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service

- name: start bind_exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - bind9
    - bind_exporter