---
- name: exporters
  hosts: linux
  become: yes
  roles:
    - node_exporter
    - apache_exporter
    - sql_exporter
    - bind

- name: prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
    - grafana